import Head from "next/head";
import { CartContent } from "../components/cart-content/cart-content";
import { MainLayout } from "app/shared/components/main-layout/main-layout";

export default function CartPage() {
  return (
    <>
      <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <CartContent />
      </MainLayout>
    </>
  );
}
