import Head from "next/head";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import { NetworkStatus } from '@apollo/client';

import { ContentGrid } from "../components/content-grid/content-grid";
import { FeaturedSection } from "../components/featured-section/featured-section";
import { Footer } from "../components/footer/Footer";
import { HeroHomepage } from "../components/hero-homepage/hero-hompage";
import { Navbar } from "../components/navbar/Navbar";
import { apolloClient } from "../graphql/apolloClient";
import {
	GetAllCategoriesByPrimaryDocument,
	GetAllCategoriesByPrimaryQuery,
} from "../generated/graphql";
import { ApolloQueryResult } from "@apollo/client";
import { MainCategories } from "main-categories/main-categories";
import { useLocale } from "hooks/useLocale/useLocale";

export const getStaticProps: GetStaticProps<{
	productCategories: {
		isLoading: boolean;
		categories: ApolloQueryResult<GetAllCategoriesByPrimaryQuery>["data"]["categories"];
	};
}> = async (_context) => {
	const primaryProductsCategories =
		await apolloClient.query<GetAllCategoriesByPrimaryQuery>({
			query: GetAllCategoriesByPrimaryDocument,
			variables: { isPrimaryCategory: true },
		});

	return {
		props: {
			productCategories: {
				isLoading: primaryProductsCategories.networkStatus === NetworkStatus.loading,
				categories: primaryProductsCategories.data.categories,
			},
		},
	};
};

export type HomeProps = InferGetStaticPropsType<typeof getStaticProps>;

export default function Home({
	productCategories,
}: HomeProps) {
	const { t } = useLocale();

	return (
		<>
			<Head>
				<title>{t('home.pageTitle')}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<HeroHomepage />
			{ productCategories.categories && <MainCategories categories={productCategories.categories} />}
			<FeaturedSection />
			<ContentGrid />
			<Footer />
		</>
	);
}
