import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/navigation";

import { LoginForm } from "../login/login-form/login-form";
import { MainLayout } from "app/shared/components/main-layout/main-layout";

export default function LoginPage() {
  const session = useSession();
  const router = useRouter();

  if (session.status === "authenticated") {
    router.push("/");
    return;
  }

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <LoginForm />
      </MainLayout>
    </>
  );
}
