import { getCsrfToken, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";

import { Footer } from "../components/footer/Footer";
import { LoginForm } from "../login/login-form/login-form";
import { Navbar } from "../components/navbar/Navbar";
import { LoginPageProps } from "login/login.types";

export default function LoginPage() {
	const session = useSession();
	const router = useRouter();

	if(session.status === 'authenticated') {
		router.push("/")
		return;
	}

	return (
		<>
			<Head>
				<title>Login</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<LoginForm />
			<Footer />
		</>
	);
}