import { useLocale } from "app/localization/hooks/useLocale";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/navigation";

import { RegisterForm } from "../components/register-form/register-form";
import { MainLayout } from "app/shared/components/main-layout/main-layout";

export default function RegisterPage() {
  const session = useSession();
  const router = useRouter();
  const { t } = useLocale();

  if (session.status === "authenticated") {
    router.push("/");
    return;
  }

  return (
    <>
      <Head>
        <title>{t("register.pageTitle")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <RegisterForm />
      </MainLayout>
    </>
  );
}
